### ISSUE TITLE
Problem in executing creating synthesis data create_real_synth_dataset.py

### ISSUE THREAD

**Issue by swagatamr** [Borda/BIRL#67]
```
Traceback (most recent call last):
  File "bm_dataset/create_real_synth_dataset.py", line 329, in <module>
    main(arg_params)
  File "bm_dataset/create_real_synth_dataset.py", line 313, in main
    for _ in mproc_pool.imap_unordered(wrapper_deform_export, range(params['nb_samples'])):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "bm_dataset/create_real_synth_dataset.py", line 263, in perform_deform_export
    image_out, points_out = deform_image_landmarks(image_out, points, max_deform)
  File "bm_dataset/create_real_synth_dataset.py", line 163, in deform_image_landmarks
    zip(x.ravel(), y.ravel()), image.reshape(-1, 3), (x + x_deform, y + y_deform), method='linear', fill_value=1.
  File "/usr/local/lib/python3.7/dist-packages/scipy/interpolate/ndgriddata.py", line 221, in griddata
    rescale=rescale)
  File "interpnd.pyx", line 245, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "interpnd.pyx", line 80, in scipy.interpolate.interpnd.NDInterpolatorBase.__init__
  File "interpnd.pyx", line 190, in scipy.interpolate.interpnd._check_init_shape
IndexError: tuple index out of range
```

#### Issue
While creating synthesis data by executing bm_dataset/create_real_synth_dataset.py  I am facing the above error .I think it might be because of the scipy version issue.
I am using  scipy==1.4.1 and also tried with scipy 1.1.10
I am using python version 3.7.13 in google colab
Please guide me and help me to solve issue

**Comment by Borda** [comment]
can you please check with any of these build docker images? https://hub.docker.com/r/borda/birl

**Comment by Borda** [comment]
Feel free re-open if the problem holds :otter:
